names=["sarah","diya","pawani","gargi","dhruv","gaurav","prateek","vani","gargi"]
print(names)
print(names[0])
print(names[1])
print(names[2])
print(names[3])
print(names[4])
print(names[5])
print(names[6])
print(names[7])
print(names[8])
print(f"hello, {names[0].title()}")
print(f"hello, {names[1].title()}")
print(f"hello, {names[2].title()}")
print(f"hello, {names[3].title()}")
print(f"hello, {names[4].title()}")
print(f"hello, {names[5].title()}")
print(f"hello, {names[6].title()}")
print(f"hello, {names[7].title()}")
print(f"hello, {names[8].title()}")