transportation=["mustang","porsche GT3 RS" ,"bentley","jaguar","rolls royce","BMW","Mercedes-Benz","AUDI","Lexus","Land Rover","Aston Marti","Lamborghini","Ferrari","BUGATTI","McLaren" ]
print(len(transportation))
print(f"I would like to own  {transportation[0].title()}.")
print(f"I would like to own  {transportation[1].title()}.")
print(f"I would like to own  {transportation[2].title()}.")
print(f"I would like to own  {transportation[3].title()}.")
print(f"I would like to own  {transportation[4].title()}.")
print(f"I would like to own  {transportation[5].title()}.")
print(f"I would like to own  {transportation[6].title()}.")
print(f"I would like to own  {transportation[7].title()}.")
print(f"I would like to own  {transportation[8].title()}.")
print(f"I would like to own  {transportation[9].title()}.")
print(f"I would like to own  {transportation[10].title()}.")
print(f"I would like to own  {transportation[11].title()}.")
print(f"I would like to own  {transportation[12].title()}.")
print(f"I would like to own  {transportation[13].title()}.")
print(f"I would like to own  {transportation[14].title()}.")